### ISSUE TITLE
A possible explanation for the "blaze-benchmark" results 

### ISSUE THREAD

**Issue by mat8913** [vacationlabs/monad-transformer-benchmark#4]
Blaze produces smaller HTML than your input.

The "constant markup via text interpolation" test writes 885117 Chars to "/tmp/output.html" whereas the "constant markup via blaze" test only writes 249907 Chars to "/tmp/output.html".

If I replace the HTML in "app/ConstantStringMarkup.hs" with the output from blaze, I get similar performance for all tests. (Edit: The "constant markup via text interpolation" actually ends up faster now)

**Comment by saurabhnanda** [comment]
Yes. You are correct. Thank you for catching this. The results were troubling me :)

I'll update the README shortly.

**Comment by saurabhnanda** [comment]
Fixed via https://github.com/vacationlabs/monad-transformer-benchmark/commit/dcdec3d6f39cb806bc85ec1543217f4475293de1

Thanks @mat8913
